# Generated by Django 2.2 on 2019-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_forumuser'),
        ('posts', '0002_auto_20190427_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='a_downvote', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='a_upvote', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvote', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to='users.ForumUser'),
        ),
    ]
