# Generated by Django 2.2 on 2019-05-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190528_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='a_downvote', to='users.ForumUser'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='a_upvote', to='users.ForumUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvote', to='users.ForumUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to='users.ForumUser'),
        ),
    ]
