# Generated by Django 2.2 on 2019-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_forumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='photo',
            field=models.ImageField(default='images/user.ico', upload_to='images/'),
        ),
    ]
