# Generated by Django 2.2 on 2019-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190531_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='photo',
            field=models.ImageField(default='images/user.ico', upload_to='images/'),
        ),
    ]
