# Generated by Django 2.2 on 2019-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190531_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='description',
            field=models.TextField(),
        ),
    ]
