# Generated by Django 2.2 on 2019-04-25 02:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('forum', '0002_auto_20190425_0157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionTags',
            new_name='QuestionTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='tags',
            new_name='tag',
        ),
    ]
