# Generated by Django 2.2 on 2019-04-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190425_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='name',
        ),
    ]
