# Generated by Django 2.2 on 2019-04-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190425_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
